# Numpy - Library to handle arrays.
- Statically typed
- Non resizable (can't append or remove elements)
- much faster than python's dynamically typed lists
- support use of vector operations

In [4]:
import numpy as np

my_array = np.array([5, 2, 6, 8])
my_array.dtype

dtype('int64')

In [5]:
a2 = np.random.random(20)
a3 = np.random.randint(10,20,10)
a3

array([19, 10, 13, 17, 11, 17, 13, 19, 16, 12])

In [8]:
a4 = np.zeros(10)
a5 = np.ones(10)
a5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
a6 = np.linspace(0,10,100)
a7 = np.arange(0,10,0.1)
a7

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])